### PR TITLE
l10n: zh-Hant: Update translation

### PR DESCRIPTION
**Pull request by pan93412**
Seems like some actions must to be taken before merging to dev.

It is exported and imported with Xcode built-in "Export Localization" function – don't worry about the format issue! 😂

I also removed the manual spacing between Chinese and English characters. macOS pads it well.

### CODE REVIEW

**Review by UeharaYou — CHANGES_REQUESTED** [review]
**PR Merge Review: Request changes.**

Thank you for contributing to Unofficial Maintenance of HiddenBar.
Unfortunately, after a brief review of your contribution, inconsistence has been found between your of zh-Hant localization and UI elements, as we found changes for some localizations have been reversed. The v2.0 Unofficial Maintenance of HiddenBar underwent some major changes on user interactions, instructions from v1.x are not applicable to v2.0. Therefore inconsistence occurs when your work is based on old (original) versions of HiddenBar (e.g. the Step by step tutorial).

Please review the enlisted conflicts before the merge can be made. Your translation is indispensable for refining the project, and also leads me a more proper way to handle localizations.

**Conflicts**
+ HiddenBar/zh-Hant.lproj/Localizable.strings: @@ -40,51 +23,24 @@, entry "Tutorial text".

**Comment by pan93412** [comment]
@UeharaYou I have corrected some inconsistent translation, and you can review it now! 😄 

Note that all translations are generated with Xcode's "Export Localization" function, ensuring consistency with the English base.

image

**Review by UeharaYou — APPROVED** [review]
PR Review: Approved.

Thank you for your work! After reviewing all file changes, your PR has been approved for it to be merged. There might be some minor fixes to your changes afterwards, but those polishing might not have to undergo another review. Again thank you very much for your contribution to the UM of HiddenBar, feel free to drop by for any advice in future development.

**Comment by UeharaYou** [comment]
> Sorry if this is the wrong place, but is it possible to install it using homebrew?

@Duckbilled Sorry I have to remove your comment from this PR thread because it is irrelevant to its topic. Please create a new issue instead. 

But just for your convenience here's your answer: No, this branch is neither notarized nor popular enough to be distributed via Homebrew (at least 75 stars) for now. Please build the product with instructions provided in "README.md" file instead.

Your comment, along with this reply, will be removed from this PR thread in 24 hours. After that you can still refer to this message via your email inbox linked with your GitHub account. Apologize for the inconvenience.

**Pull request merged**
